/*
WHAT IS DOM.?
1.THE DOM IS NOT PART OF THE JAVASCTIPT LANGUAGE BUT IS INSTEAD A WE API USED TO BUILD WEBSITES.
2.THE DOM WAS DESIGNED TO BE INDEPENDET OF ANY PARTICULAR PROGRAMMING LANGUAGE.
3.THE BROWSER CREATES THE DOM TO  RENDER THE PAGE
4.THE BROWSER GIVES JAVASCRIPT ACCESS TO THE DOM WHICH IS A PROGRAMMING LANGUAGE
5.THE DOM IS NOT A PART OF JAVASCRIPT ENGINE
6.BROWSER GIVES THE DOM API FINCTION LIKE GETELEMENTBYID(),CREATEELEMENT() ETC.AND THESE FUNCTION ARE NOT FROM JAVASCRIPT BUT THESE ALL ARE PROVIDED BY DOM API
7.IN ORDER TO SPEAK WITH DOM THE BROWSER GIVES US ACCESS DOM API APPLICATION PROGGRAMMING INTERFACE.
8.JAVASCRIP IS PROGRAMMING LANGUAGE THAT BROWSERS CAN EXECUTE.
9.WE CAN DIVIDE THE BROWSER INTO TWO COMPONENTS
1. DOM
2. JAVASCRIPT ENGINE
10.DOM API IS THE BRIDGE BETWEEN THE DOM AND JAVASCRIPT ENGINE
11.THE JAVASCRIPT ENGINE IS ALSO PRESENT IN THE BROWSER INDEPENDENTLY.

*/